### ISSUE TITLE
Consider forking from main Marlin repo

### ISSUE THREAD

**Issue by dfrencham** [jlcook83/Wanhao-Plus-BLTouch#1]
Have you considered forking from the main Marlin repo?

https://github.com/MarlinFirmware/Marlin/releases/tag/1.1.3

If you fork from there _then_  re-apply the changes using a diff tool, you will be able to merge down new Marlin versions quite easily, instead of having to do manual baseless merges.

**Comment by jlcook83** [comment]
Makes sense, I will do this when I get some free time, thanks
